apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-pvc
  namespace: lab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd    # This StorageClass does NOT exist in kind
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: lab
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres
          image: busybox:1.35
          command: ["sh", "-c", "echo 'DB ready'; sleep 3600"]
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data-volume
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: app-data-pvc
