apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: lab
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: busybox:v2.1.0-nonexistent   # This tag does not exist
          command: ["sh", "-c", "echo 'Frontend running'; sleep 3600"]
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
