apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: audit-sa-pod-reader
subjects:
  - kind: ServiceAccount
    name: audit-sa
    namespace: lab
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
